/**
 * Seeds one global SiteTemplate per industry blueprint.
 *
 * Rather than hand-authoring templates as a separate content type, each one
 * is generated by running the SAME deterministic compiler the "no AI
 * configured" generation path uses (`blueprintSpec` + `compileSite`). Two
 * benefits from that:
 *
 *   1. Zero drift. A template can never fall out of sync with what
 *      generation actually produces, because it IS what generation produces.
 *   2. Coverage for free. Every industry blueprint automatically has a
 *      matching template gallery entry — add a blueprint, get a template.
 *
 * Templates store a `blueprint: { theme, pages }` JSON blob (see the
 * SiteTemplate model comment), which `siteTemplateService.apply()` copies
 * into a new site's theme + pages verbatim, the same shape
 * `buildStarterDocument` already produces for a brand-new site.
 *
 * Run with: npm run db:seed:templates
 */

import { PrismaClient } from "@prisma/client";
import { getBlueprint, listBlueprints } from "../../src/site/ai/blueprints";
import { blueprintSpec, compileSite } from "../../src/site/ai/compile";
import { siteTemplateRepository } from "../../src/server/repositories/siteTemplate.repository";

const prisma = new PrismaClient();

/** Placeholder business identity used only to generate template copy. */
function sampleContext(industry: string, name: string, city: string) {
  return { businessName: name, industry, city, country: null, phone: "+1 555 0100" };
}

/** One representative sample business per industry, for believable template copy. */
const SAMPLES: Record<string, { name: string; city: string }> = {
  hospital: { name: "Riverside General Hospital", city: "Austin" },
  clinic: { name: "Wellview Family Clinic", city: "Denver" },
  dental: { name: "Bright Smile Dental", city: "Seattle" },
  restaurant: { name: "Olive & Thyme", city: "Portland" },
  cafe: { name: "The Daily Grind", city: "Boulder" },
  hotel: { name: "Harbor View Hotel", city: "San Diego" },
  gym: { name: "Ironclad Fitness", city: "Miami" },
  salon: { name: "Luxe Hair Studio", city: "Nashville" },
  spa: { name: "Serenity Day Spa", city: "Scottsdale" },
  school: { name: "Lakeside Academy", city: "Raleigh" },
  realestate: { name: "Summit Realty Group", city: "Charlotte" },
  lawfirm: { name: "Whitfield & Cross Law", city: "Chicago" },
  agency: { name: "Northstar Digital", city: "Brooklyn" },
  retail: { name: "Maple & Co.", city: "Minneapolis" },
  automotive: { name: "Precision Auto Care", city: "Phoenix" },
};

async function main() {
  const blueprints = listBlueprints();
  console.log(`Seeding ${blueprints.length} global site templates...`);

  let order = 0;
  for (const blueprint of blueprints) {
    const sample = SAMPLES[blueprint.key] ?? { name: blueprint.label, city: "" };
    const ctx = sampleContext(blueprint.label, sample.name, sample.city);

    // The compiler resolves the blueprint from the free-text industry label, so
    // a label that resolves to a *different* blueprint would silently seed the
    // wrong template under the right name. That is exactly what happened with
    // "Dental clinic" resolving to the clinic blueprint. Fail loudly instead.
    const resolved = getBlueprint(blueprint.label);
    if (resolved.key !== blueprint.key) {
      throw new Error(
        `Blueprint label "${blueprint.label}" resolves to "${resolved.key}", expected "${blueprint.key}". ` +
          `Fix resolveIndustryKey() in src/site/document/theme.ts before seeding.`,
      );
    }

    // demoContent fills staff and reviewer names with plausible samples. A
    // gallery template is understood to be demo content, and four cards all
    // reading "Team member" makes a finished design look unfinished. The
    // no-AI fallback path for real tenant sites leaves this off.
    const spec = blueprintSpec(ctx, { demoContent: true });
    const compiled = compileSite(spec, ctx);

    const blueprintJson = {
      theme: compiled.theme,
      pages: compiled.pages.map((p) => ({
        title: p.title,
        path: p.path,
        isHome: p.isHome,
        document: p.document,
        seo: p.seo,
      })),
    };

    const template = await siteTemplateRepository.upsertGlobalBySlug(blueprint.key, {
      tenantId: null,
      name: blueprint.label,
      industry: blueprint.label,
      description: `A ready-to-edit ${blueprint.label.toLowerCase()} website with ${compiled.pages.length} pages — home, ${compiled.pages
        .filter((p) => !p.isHome)
        .map((p) => p.title.toLowerCase())
        .join(", ")}.`,
      blueprint: blueprintJson as object,
      isGlobal: true,
      isPremium: false,
      sortOrder: order,
    });

    console.log(`  ✓ ${template.slug} (${compiled.pages.length} pages)`);
    order += 1;
  }

  console.log("Done.");
}

main()
  .catch((err) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
